# Generated by Django 3.2 on 2021-04-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('earliest_date', models.DateTimeField(null=True)),
                ('latest_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('file_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mediatype', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=16)),
                ('file_location', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('date_taken', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mopho.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mopho.album')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mopho.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mopho.mediafile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mopho.tag')),
            ],
            options={
                'unique_together': {('media_file', 'tag')},
            },
        ),
    ]
