# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('sha256sum', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mediatype', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=16)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('date_taken', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaFileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mopho.MediaFile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='mediafiletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mopho.Tag'),
        ),
    ]
