# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_location',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='date_taken',
            field=models.DateTimeField(),
        ),
    ]
