# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0002_auto_20160803_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mopho.MediaFile')),
            ],
        ),
        migrations.AlterField(
            model_name='mediafiletag',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mopho.MediaFile'),
        ),
    ]
