# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0003_auto_20160803_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file_location',
            field=models.CharField(max_length=1024),
        ),
    ]
