# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0006_auto_20160803_2349'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediafiletag',
            unique_together=set([('media_file', 'tag')]),
        ),
    ]
