# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0007_auto_20160803_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='album_name',
            field=models.CharField(default='DEF', max_length=1024),
            preserve_default=False,
        ),
    ]
