# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0009_auto_20160907_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='albumitem',
            name='file_location',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
