# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0010_auto_20160907_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='earliest_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='latest_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='albumitem',
            name='file_location',
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
    ]
