# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0011_auto_20160907_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_location',
            field=models.CharField(db_index=True, default='', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
