# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopho', '0012_mediafile_file_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
    ]
