# Generated by Django 3.2.6 on 2021-08-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.ManyToManyField(through='core.MediaFileTag', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='mediafilecomment',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.mediafile'),
        ),
    ]
