# Generated by Django 3.2.6 on 2021-08-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210811_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-latest_date', '-id']},
        ),
        migrations.AlterField(
            model_name='album',
            name='latest_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
