# Generated by Django 4.2.7 on 2023-12-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_latest_date_db_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumitem',
            options={'ordering': ['-id']},
        ),
    ]
